spring.jmx.enabled=false
javafx.title=MyDemoApplication
javafx.stage.resizable=true
logging.level.net.lustenauer=debug
logging.level.root=INFO
logging.level.com.sun.javafx.application.PlatformImpl=OFF